# coding: utf-8

"""
    Rakam API Documentation

    An analytics platform API that lets you create your own analytics services.

    OpenAPI spec version: 0.5
    Contact: contact@rakam.io
    Generated by: https://github.com/swagger-api/swagger-codegen.git

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
"""

from __future__ import absolute_import

import os
import sys
import unittest

import rakam_client
from rakam_client.rest import ApiException
from rakam_client.apis.user_api import UserApi


class TestUserApi(unittest.TestCase):
    """ UserApi unit test stubs """

    def setUp(self):
        self.api = rakam_client.apis.user_api.UserApi()

    def tearDown(self):
        pass

    def test_create_segment(self):
        """
        Test case for create_segment

        Get events of the user
        """
        pass

    def test_create_user(self):
        """
        Test case for create_user

        Create new user
        """
        pass

    def test_create_users(self):
        """
        Test case for create_users

        Create multiple new users
        """
        pass

    def test_get_events(self):
        """
        Test case for get_events

        Get events of the user
        """
        pass

    def test_get_metadata(self):
        """
        Test case for get_metadata

        Get user storage metadata
        """
        pass

    def test_get_user(self):
        """
        Test case for get_user

        Get user
        """
        pass

    def test_increment_property(self):
        """
        Test case for increment_property

        Set user property
        """
        pass

    def test_search_users(self):
        """
        Test case for search_users

        Search users
        """
        pass

    def test_set_properties(self):
        """
        Test case for set_properties

        Set user properties
        """
        pass

    def test_set_properties_once(self):
        """
        Test case for set_properties_once

        Set user properties once
        """
        pass

    def test_unset_property(self):
        """
        Test case for unset_property

        Unset user property
        """
        pass


if __name__ == '__main__':
    unittest.main()
