# coding: utf-8

"""
    Rakam API Documentation

    An analytics platform API that lets you create your own analytics services.

    OpenAPI spec version: 0.5
    Contact: contact@rakam.io
    Generated by: https://github.com/swagger-api/swagger-codegen.git

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
"""

from pprint import pformat
from six import iteritems
import re


class Stats(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, all_events=None, monthly_events=None, daily_events=None):
        """
        Stats - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'all_events': 'int',
            'monthly_events': 'int',
            'daily_events': 'int'
        }

        self.attribute_map = {
            'all_events': 'allEvents',
            'monthly_events': 'monthlyEvents',
            'daily_events': 'dailyEvents'
        }

        self._all_events = all_events
        self._monthly_events = monthly_events
        self._daily_events = daily_events

    @property
    def all_events(self):
        """
        Gets the all_events of this Stats.


        :return: The all_events of this Stats.
        :rtype: int
        """
        return self._all_events

    @all_events.setter
    def all_events(self, all_events):
        """
        Sets the all_events of this Stats.


        :param all_events: The all_events of this Stats.
        :type: int
        """

        self._all_events = all_events

    @property
    def monthly_events(self):
        """
        Gets the monthly_events of this Stats.


        :return: The monthly_events of this Stats.
        :rtype: int
        """
        return self._monthly_events

    @monthly_events.setter
    def monthly_events(self, monthly_events):
        """
        Sets the monthly_events of this Stats.


        :param monthly_events: The monthly_events of this Stats.
        :type: int
        """

        self._monthly_events = monthly_events

    @property
    def daily_events(self):
        """
        Gets the daily_events of this Stats.


        :return: The daily_events of this Stats.
        :rtype: int
        """
        return self._daily_events

    @daily_events.setter
    def daily_events(self, daily_events):
        """
        Sets the daily_events of this Stats.


        :param daily_events: The daily_events of this Stats.
        :type: int
        """

        self._daily_events = daily_events

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
