# coding: utf-8

"""
    Rakam API Documentation

    An analytics platform API that lets you create your own analytics services.

    OpenAPI spec version: 0.5
    Contact: contact@rakam.io
    Generated by: https://github.com/swagger-api/swagger-codegen.git

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
"""

from pprint import pformat
from six import iteritems
import re


class UserIncrementProperty(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, api=None, id=None, _property=None, value=None):
        """
        UserIncrementProperty - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'api': 'UserContext',
            'id': 'str',
            '_property': 'str',
            'value': 'float'
        }

        self.attribute_map = {
            'api': 'api',
            'id': 'id',
            '_property': 'property',
            'value': 'value'
        }

        self._api = api
        self._id = id
        self.__property = _property
        self._value = value

    @property
    def api(self):
        """
        Gets the api of this UserIncrementProperty.


        :return: The api of this UserIncrementProperty.
        :rtype: UserContext
        """
        return self._api

    @api.setter
    def api(self, api):
        """
        Sets the api of this UserIncrementProperty.


        :param api: The api of this UserIncrementProperty.
        :type: UserContext
        """

        self._api = api

    @property
    def id(self):
        """
        Gets the id of this UserIncrementProperty.


        :return: The id of this UserIncrementProperty.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """
        Sets the id of this UserIncrementProperty.


        :param id: The id of this UserIncrementProperty.
        :type: str
        """

        self._id = id

    @property
    def _property(self):
        """
        Gets the _property of this UserIncrementProperty.


        :return: The _property of this UserIncrementProperty.
        :rtype: str
        """
        return self.__property

    @_property.setter
    def _property(self, _property):
        """
        Sets the _property of this UserIncrementProperty.


        :param _property: The _property of this UserIncrementProperty.
        :type: str
        """

        self.__property = _property

    @property
    def value(self):
        """
        Gets the value of this UserIncrementProperty.


        :return: The value of this UserIncrementProperty.
        :rtype: float
        """
        return self._value

    @value.setter
    def value(self, value):
        """
        Sets the value of this UserIncrementProperty.


        :param value: The value of this UserIncrementProperty.
        :type: float
        """

        self._value = value

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
